
    // All cars with full specs
export const allCars = [
    {
        id: "c001",
        name: "Toyota Probox 2016",
        brand: "Toyota",
        year: "2016",
        price: 750000,
        img: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502941/probox_irije1.webp",
        imgFront: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502941/probox_irije1.webp",
        imgRear: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502941/probox_irije1.webp",
        imgDashboard: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502941/probox_irije1.webp",
        imgSide: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502941/probox_irije1.webp",
        specs: {
            engine: "1.5L Inline-4",
            fuel: "Petrol",
            transmission: "5-Speed Manual",
            drivetrain: "FWD",
            color: "White",
            mileage: "98,000 km",
            seats: "5",
            horsepower: "103 hp",
            torque: "132 Nm",
            infotainment: "Basic Radio, USB",
            safety: "2 Airbags, ABS, Seatbelt Warning"
        }
    },
    {
        id: "c002",
        name: "Toyota Vitz 2015",
        brand: "Toyota",
        year: "2015",
        price: 830000,
        img: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502949/honda-civic_anydtk.webp",
        imgFront: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502949/honda-civic_anydtk.webp",
        imgRear: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502949/honda-civic_anydtk.webp",
        imgDashboard: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502949/honda-civic_anydtk.webp",
        imgSide: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502949/honda-civic_anydtk.webp",
        specs: {
            Engine: "1.3L",
            Transmission: "Automatic",
            Fuel: "Petrol",
            Mileage: "67,000 km",
            Drive: "2WD",
            Color: "Silver",
            Interior: "Fabric",
            Doors: "5",
            Seats: "5"
        }
    },
    {
        id: "c003",
        name: "Audi A4 2018",
        brand: "Audi",
        year: "2018",
        price: 2499000,
        img: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745503068/audi-a4_xnkpsn.webp",
        imgFront: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745503068/audi-a4_xnkpsn.webp",
        imgRear: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745503068/audi-a4_xnkpsn.webp",
        imgDashboard: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745503068/audi-a4_xnkpsn.webp",
        imgSide: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745503068/audi-a4_xnkpsn.webp",
        specs: {
            Engine: "2.0L Turbo",
            Transmission: "Automatic",
            Fuel: "Petrol",
            Mileage: "45,000 km",
            Drive: "AWD",
            Color: "Black",
            Interior: "Leather",
            Doors: "4",
            Seats: "5"
        }
    },
    {
        id: "c004",
        name: "Nissan X-Trail 2020",
        brand: "Nissan",
        year: "2020",
        price: 2750000,
        img: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745503058/nissan-xtrail_ul6n6j.webp",
        imgFront: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745503058/nissan-xtrail_ul6n6j.webp",
        imgRear: "/images/nissan-xtrail.webp",
        imgDashboard: "/images/nissan-xtrail.webp",
        imgSide: "/images/nissan-xtrail.webp",
        specs: {
            engine: "2.0L Inline-4",
            fuel: "Petrol",
            transmission: "CVT Automatic",
            drivetrain: "4WD",
            color: "Gun Metallic",
            mileage: "40,000 km",
            seats: "5",
            horsepower: "142 hp",
            torque: "200 Nm",
            infotainment: "8\" Display, Android Auto, Apple CarPlay",
            safety: "360° Camera, Emergency Brake, Traction Control"
        }
    },
    {
        id: "c005",
        name: "Toyota Mark X 2019",
        brand: "Toyota",
        year: "2019",
        price: 2350000,
        img: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502904/mark-x_prnfnj.webp",
        imgFront: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502904/mark-x_prnfnj.webp",
        imgRear: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502904/mark-x_prnfnj.webp",
        imgDashboard: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502904/mark-x_prnfnj.webp",
        imgSide: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502904/mark-x_prnfnj.webp",
        specs: {
            engine: "2.5L V6",
            fuel: "Petrol",
            transmission: "6-Speed Automatic",
            drivetrain: "RWD",
            color: "Silver",
            mileage: "52,000 km",
            seats: "5",
            horsepower: "203 hp",
            torque: "243 Nm",
            infotainment: "Touchscreen, Reverse Camera, USB, Bluetooth",
            safety: "ABS, 6 Airbags, Lane Departure Alert, Auto Braking"
        }
    },
    {
        id: "c006",
        name: "Audi RS8 2019",
        brand: "Audi",
        year: "2019",
        price: 13500000,
        img: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502830/rs8_n6pozx.webp",
        imgFront: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502830/rs8_n6pozx.webp",
        imgRear: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502830/rs8_n6pozx.webp",
        imgDashboard: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502830/rs8_n6pozx.webp",
        imgSide: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502830/rs8_n6pozx.webp",
        specs: {
            engine: "4.0L Twin-Turbo V8",
            fuel: "Petrol",
            transmission: "8-Speed Tiptronic",
            drivetrain: "Quattro AWD",
            color: "Daytona Grey",
            mileage: "30,000 km",
            seats: "5",
            horsepower: "591 hp",
            torque: "800 Nm",
            infotainment: "Virtual Cockpit, MMI Nav, Bang & Olufsen Audio",
            safety: "Adaptive Cruise, Parking Sensors, Lane Departure Warning"
        }
    },
    {
        id: "c007",
        name: "Toyota Prado V8 2020",
        brand: "Toyota",
        year: "2020",
        price: 8500000,
        img: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502839/toyota-v8_hgkbad.webp",
        imgFront: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502839/toyota-v8_hgkbad.webp",
        imgRear: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502839/toyota-v8_hgkbad.webp",
        imgDashboard: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502839/toyota-v8_hgkbad.webp",
        imgSide: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502839/toyota-v8_hgkbad.webp",
        specs: {
            engine: "4.6L V8 Petrol",
            fuel: "Petrol",
            transmission: "6-Speed Automatic",
            drivetrain: "4WD",
            color: "Pearl White",
            mileage: "45,000 km",
            seats: "7",
            horsepower: "301 hp",
            torque: "439 Nm",
            infotainment: "Touchscreen, Navigation, Bluetooth",
            safety: "Airbags, ABS, Lane Assist, Reverse Camera"
        }
    },
    {
        id: "c008",
        name: "Mazda Demio 2017",
        brand: "Mazda",
        year: "2017",
        price: 890000,
        img: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502946/demio_c2n8z0.webp",
        imgFront: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502946/demio_c2n8z0.webp",
        imgRear: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502946/demio_c2n8z0.webp",
        imgDashboard: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502946/demio_c2n8z0.webp",
        imgSide: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502946/demio_c2n8z0.webp",
        specs: {
            Engine: "1.5L",
            Transmission: "Automatic",
            Fuel: "Petrol",
            Mileage: "51,000 km",
            Drive: "2WD",
            Color: "Red",
            Interior: "Cloth",
            Doors: "5",
            Seats: "5"
        }
    },
    {
        id: "c009_white",
        name: "Honda Civic 2019 - White",
        brand: "Honda",
        year: "2019",
        price: 1250000,
        img: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502949/honda-civic_anydtk.webp",
        imgFront: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502949/honda-civic_anydtk.webp",
        imgRear: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502949/honda-civic_anydtk.webp",
        imgDashboard: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502949/honda-civic_anydtk.webp",
        imgSide: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502949/honda-civic_anydtk.webp",
        specs: {
            Engine: "2.0L",
            Transmission: "Automatic",
            Fuel: "Petrol",
            Mileage: "40,000 km",
            Drive: "FWD",
            Color: "White",
            Interior: "Fabric",
            Doors: "4",
            Seats: "5"
        }
    },
    {
        id: "c009_black",
        name: "Honda Civic 2019 - Black",
        brand: "Honda",
        year: "2019",
        price: 1300000,
        img: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502949/honda-civic_anydtk.webp",
        imgFront: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502949/honda-civic_anydtk.webp",
        imgRear: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502949/honda-civic_anydtk.webp",
        imgDashboard: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502949/honda-civic_anydtk.webp",
        imgSide: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745502949/honda-civic_anydtk.webp",
        specs: {
            Engine: "2.0L",
            Transmission: "Automatic",
            Fuel: "Petrol",
            Mileage: "45,000 km",
            Drive: "FWD",
            Color: "Black",
            Interior: "Fabric",
            Doors: "4",
            Seats: "5"
        }
    },
    {
        id: "c010_red",
        name: "Ford Mustang 2020 - Red",
        brand: "Ford",
        year: "2020",
        price: 5200000,
        img: "/images/mustang.webp",
        imgFront: "/images/mustang.webp",
        imgRear: "/images/mustang.webp",
        imgDashboard: "/images/mustang.webp",
        imgSide: "/images/mustang.webp",
        specs: {
            Engine: "5.0L V8",
            Transmission: "Automatic",
            Fuel: "Petrol",
            Mileage: "30,000 km",
            Drive: "RWD",
            Color: "Red",
            Interior: "Leather",
            Doors: "2",
            Seats: "4"
        }
    },
    {
        id: "c010_blue",
        name: "Ford Mustang 2020 - Blue",
        brand: "Ford",
        year: "2020",
        price: 5500000,
        img: "https://res.cloudinary.com/dejq3evca/image/upload//f_auto,q_auto/v1745510310/mustang_jhfgf5.webp",
        imgFront: "https://res.cloudinary.com/dejq3evca/image/upload//f_auto,q_auto/v1745510310/mustang_jhfgf5.webp",
        imgRear: "https://res.cloudinary.com/dejq3evca/image/upload//f_auto,q_auto/v1745510310/mustang_jhfgf5.webp",
        imgDashboard: "https://res.cloudinary.com/dejq3evca/image/upload//f_auto,q_auto/v1745510310/mustang_jhfgf5.webp",
        imgSide: "https://res.cloudinary.com/dejq3evca/image/upload//f_auto,q_auto/v1745510310/mustang_jhfgf5.webp",
        specs: {
            Engine: "5.0L V8",
            Transmission: "Automatic",
            Fuel: "Petrol",
            Mileage: "25,000 km",
            Drive: "RWD",
            Color: "Blue",
            Interior: "Leather",
            Doors: "2",
            Seats: "4"
        }
    },
    {
        id: "c011_silver",
        name: "Nissan X-Trail 2020 - Silver",
        brand: "Nissan",
        year: "2020",
        price: 3700000,
        img: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745503058/nissan-xtrail_ul6n6j.webp",
        imgFront: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745503058/nissan-xtrail_ul6n6j.webp",
        imgRear: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745503058/nissan-xtrail_ul6n6j.webp",
        imgDashboard: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745503058/nissan-xtrail_ul6n6j.webp",
        imgSide: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745503058/nissan-xtrail_ul6n6j.webp",
        specs: {
            Engine: "2.5L",
            Transmission: "CVT",
            Fuel: "Petrol",
            Mileage: "35,000 km",
            Drive: "AWD",
            Color: "Silver",
            Interior: "Leather",
            Doors: "5",
            Seats: "5"
        }
    },
    {
        id: "c011_white",
        name: "Nissan X-Trail 2020 - White",
        brand: "Nissan",
        year: "2020",
        price: 3750000,
        img: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745503058/nissan-xtrail_ul6n6j.webp",
        imgFront: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745503058/nissan-xtrail_ul6n6j.webp",
        imgRear: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745503058/nissan-xtrail_ul6n6j.webp",
        imgDashboard: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745503058/nissan-xtrail_ul6n6j.webp",
        imgSide: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745503058/nissan-xtrail_ul6n6j.webp",
        specs: {
            Engine: "2.5L",
            Transmission: "CVT",
            Fuel: "Petrol",
            Mileage: "33,000 km",
            Drive: "AWD",
            Color: "White",
            Interior: "Leather",
            Doors: "5",
            Seats: "5"
        }
    },
    {
        id: "c012_blue",
        name: "BMW 3 Series 2020 - Blue",
        brand: "BMW",
        year: "2020",
        price: 4200000,
        img: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745503047/bmw-3_apnm4a.webp",
        imgFront: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745503047/bmw-3_apnm4a.webp",
        imgRear: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745503047/bmw-3_apnm4a.webp",
        imgDashboard: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745503047/bmw-3_apnm4a.webp",
        imgSide: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745503047/bmw-3_apnm4a.webp",
        specs: {
            Engine: "2.0L",
            Transmission: "Automatic",
            Fuel: "Petrol",
            Mileage: "40,000 km",
            Drive: "RWD",
            Color: "Blue",
            Interior: "Leather",
            Doors: "4",
            Seats: "5"
        }
    },
    {
        id: "c012_black",
        name: "BMW 3 Series 2020 - Black",
        brand: "BMW",
        year: "2020",
        price: 4300000,
        img: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745503047/bmw-3_apnm4a.webp",
        imgFront: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745503047/bmw-3_apnm4a.webp",
        imgRear: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745503047/bmw-3_apnm4a.webp",
        imgDashboard: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745503047/bmw-3_apnm4a.webp",
        imgSide: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745503047/bmw-3_apnm4a.webp",
        specs: {
            Engine: "2.0L",
            Transmission: "Automatic",
            Fuel: "Petrol",
            Mileage: "30,000 km",
            Drive: "RWD",
            Color: "Black",
            Interior: "Leather",
            Doors: "4",
            Seats: "5"
        }
    },
    {
        id: "c013_green",
        name: "Range Rover Evoque 2019 - Green",
        brand: "Range Rover",
        year: "2019",
        price: 6000000,
        img: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745503021/rangerover-evoque_say4fl.webp",
        imgFront: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745503021/rangerover-evoque_say4fl.webp",
        imgRear: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745503021/rangerover-evoque_say4fl.webp",
        imgDashboard: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745503021/rangerover-evoque_say4fl.webp",
        imgSide: "https://res.cloudinary.com/dejq3evca/image/upload/f_auto,q_auto/v1745503021/rangerover-evoque_say4fl.webp",
        specs: {
            Engine: "2.0L",
            Transmission: "Automatic",
            Fuel: "Petrol",
            Mileage: "50,000 km",
            Drive: "AWD",
            Color: "Green",
            Interior: "Leather",
            Doors: "5",
            Seats: "5"
        }
    },
];